# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GCal-to-Notion

on:
  push:
    branches: [ "main" ]
  watch:
    types: [ "started" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # with: 
      #   token: ${{ secrets.GH_TOKEN }}
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install requests
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run
      env: 
        NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        GCalURL: ${{ secrets.GCalURL }}
      run: |
        python main.py $GCalURL $NOTION_TOKEN $NOTION_DB_ID
    
    - name: Commit files
      run: |
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "Change History.csv" -a
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
        force: true
