# Clone GCal-to-Notion-dev to GCal-to-Notion except history.csv

name: Publish to GCal-to-Notion

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
        
      # - name: Remove History.csv
      #   run: |
      #     rm history.csv
      
      - name: Push
        run: |
          git config --local user.email "github_actions[bot]@noreply.mail.github.com"
          git config --local user.name "github_actions[bot]"
          git add .
          git restore --staged history.csv
          git commit --allow-empty -m "Auto Release"
        
      - name: Push
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          repository: minhung1126/GCal-to-Notion
          force: true